version: '3.5'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks: 
      - services
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      services:
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks: 
      - services
  rabbitmq:
    image: rabbitmq:3.8.11-management-alpine
    container_name: rabbitmq
#    volumes:
#        - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
#        - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
#        - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
        RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - services
networks:
  services:
    external: true